on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing BYOB
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date)"
      - id: machine
        run: echo "##[set-output name=data;]$(hostname)"
      - name: Stuff
        uses: RubbaBoy/BYOB@v1.0.0-SNAPSHOT.19
        with:
          NAME: time
          LABEL: 'Updated at'
          STATUS: ${{ steps.date.outputs.data }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Stuff
        uses: RubbaBoy/BYOB@v1.0.0-SNAPSHOT.19
        with:
          NAME: machine
          LABEL: 'Hostname'
          STATUS: ${{ steps.machine.outputs.data }}
          COLOR: FFC0CB
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
