on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      - uses: actions/checkout@v1
      - name: Shit
        uses: RubbaBoy/BYOB@v1.0.0-SNAPSHOT.1
        with:
          NAME: first
          LABEL: huh
          STATUS: ${{ date }}
          COLOR: 00EEFF
