on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing BYOB
    steps:
      - uses: actions/checkout@v1
      - id: data
        run: echo "##[set-output name=data;]$(hostname)"
      - name: Stuff
        uses: RubbaBoy/BYOB@v1.0.0-SNAPSHOT.3
        with:
          NAME: first
          LABEL: huh
          STATUS: ${{ steps.data.outputs.data }}
          COLOR: 00EEFF
